export const COPY_KO = {
	view: {
		title: "노트 연결 보기",
		openRibbon: "현재 노트 연결 보기",
		openCanvasCommand: "고급: Canvas 열기 또는 만들기",
		helpCommand: "노트 연결 보기 사용 방법",
		openCommand: "현재 노트 연결 보기",
		createCanvasCommand: "고급: 현재 노트로 Canvas 만들기",
		enableCanvasCommand: "고급: 현재 Canvas에 링크 카드 추가",
		refreshCanvasCommand: "고급: 현재 Canvas 링크 새로고침",
		manageCommand: "고급: 저장된 그래프 목록",
		refreshCommand: "현재 노트 연결 새로고침",
		aria: "지식 그래프. 드래그로 이동하고 마우스 휠로 확대 또는 축소합니다.",
	},
	actions: {
		searchGraph: "그래프 검색",
		filterRelations: "관계 표시 설정",
		continueInCanvas: "Canvas에서 계속",
		expandNeighbours: "주변 노트 펼치기",
		collapseNeighbours: "주변 노트 접기",
		expandNeighboursCount: (count: number) => `주변 노트 ${count}개 펼치기`,
		collapseNeighboursCount: (count: number) => count === 0
			? "주변 펼침 해제 (숨겨지는 노트 없음)"
			: `주변 노트 ${count}개 접기`,
		removeFromGraph: "그래프에서 제거",
		newCard: "새 카드",
		createCard: "새 카드 만들기",
		zoomIn: "확대",
		zoomOut: "축소",
		resetView: "전체 그래프 맞추기",
		dragToConnect: "연결점에서 끌기",
		pinCard: "다른 카드를 열어도 이 카드 유지",
		unpinCard: "카드 유지 해제",
		editCard: "카드에서 Markdown 편집",
		finishEditing: "편집 마치고 읽기 모드로 전환",
		selectDraft: "내 편집 선택",
		reloadSource: "원문 다시 불러오기",
		openSource: "원문 열기",
		openSourceBesideGraph: "원본을 오른쪽 편집기로 열기",
		more: "더보기",
		moveToTrash: "원본 노트를 휴지통으로 이동…",
		cancel: "취소",
	},
	labels: {
		roleRoot: "시작",
		roleTopic: "주제",
		roleEntity: "개체",
		roleQuestion: "질문",
		searchPlaceholder: "카드 제목·요약·본문 검색",
		relationFilters: "표시할 관계",
		searchNoResults: "일치하는 카드가 없습니다",
		searchPanel: "그래프 검색 및 관계 표시",
		graphToolbar: "그래프 도구",
		cardLoading: "Markdown을 불러오는 중…",
		currentNoteGraphName: (title: string) => `${title} 주변`,
		newTopicTitle: "새 주제",
		inlineMarkdownEditor: "원본 Markdown 편집기",
		emptyTitle: "포함된 노트가 없습니다",
		emptyFolderScope: (folder: string) => `“${folder}” 범위에서 그래프에 포함할 노트를 찾지 못했습니다.`,
		emptyCuratedScope: "이 그래프에는 아직 직접 추가한 노트가 없습니다.",
		emptyAllScope: "이 그래프에 표시할 노트가 아직 없습니다.",
		emptyNextStep: "Markdown 노트를 연 뒤 연결된 노트 읽기 지도를 시작하세요.",
		noVisibleLinks: "아직 연결된 노트가 없습니다. wikilink나 backlink를 추가하면 이 지도가 자랍니다.",
	},
	relations: {
		derived: "맥락",
		related: "관련",
		prerequisite: "선수 지식",
		supports: "근거",
		contrasts: "비교·반례",
		"follow-up": "후속 질문",
	},
	settings: {
		helpName: "노트 연결 보기 시작하기",
		helpDescription: "노트의 wikilink를 따라가고 필요할 때만 Canvas를 사용하는 흐름을 확인합니다.",
		helpButton: "사용 방법",
		graphSettingsDescription: "저장된 그래프마다 물리 설정을 독립적으로 보관합니다.",
		physicsDescription: "그래프의 모든 카드가 서로 밀고 연결선이 당기는 정도를 조절합니다. 화면 위치나 Markdown 내용은 바꾸지 않습니다.",
		linkStrengthName: "연결 강도",
		linkStrengthDescription: "연결된 카드가 서로 끌어당기는 힘입니다. 높을수록 연결된 항목이 가깝게 유지됩니다.",
		repulsionName: "반발력",
		repulsionDescription: "모든 카드가 서로 밀어내는 힘입니다. 높을수록 그래프가 넓게 퍼집니다.",
		linkGapName: "연결 간격",
		linkGapDescription: "연결된 카드 테두리 사이의 기본 여백입니다. 높을수록 관계선이 길어집니다.",
	},
	help: {
		title: "노트의 연결을 어떻게 볼까요?",
		intro: "Markdown 노트의 [[wikilink]]와 backlink가 관계의 정본입니다. 노트를 연 뒤 연결 보기를 실행하고, 파란 링크를 눌러 원본 문서로 이동하세요.",
		canvasEyebrow: "1 · 노트에서 이동",
		canvasTitle: "하이퍼링크가 기본 탐색",
		canvasDescription: "Wiki 노트의 파란 링크를 누르면 연결된 원본 노트가 열립니다. 별도 Map이나 Canvas를 만들 필요가 없습니다.",
		mapEyebrow: "2 · 연결을 한눈에 보기",
		mapTitle: "현재 노트 연결 보기",
		mapDescription: "현재 노트의 실제 wikilink·embed·backlink만 보조 그래프로 펼칩니다. 카드를 열어 읽고 원본 편집기로 이동할 수 있습니다.",
		existingEyebrow: "3 · 필요할 때만 공간 배치",
		existingTitle: "Canvas는 고급 도구",
		existingDescription: "여러 Markdown·PDF·이미지를 자유롭게 배치해야 할 때만 표준 Canvas를 사용합니다. 일상적인 Wiki 탐색에는 필요하지 않습니다.",
		ownershipTitle: "무엇이 바뀌고, 무엇이 그대로인가요?",
		ownershipItems: [
			"원본 Markdown의 wikilink가 문서 관계의 유일한 정본입니다.",
			"노트 연결 보기는 링크를 읽을 뿐 별도 지식이나 관계를 저장하지 않습니다.",
			"표준 .canvas는 위치·크기·그룹과 수동 공간 메모만 소유하며 Markdown을 변경하지 않습니다.",
			"Canvas의 선택적 sidecar는 배치할 파일 범위만 보관하고 원문을 복제하지 않습니다.",
		],
		openCanvas: "고급 Canvas 열기",
		openMap: "현재 노트 연결 보기",
	},
	modal: {
		canvasLauncherPlaceholder: "고급 Canvas 작업: 새로 만들거나 기존 파일 열기…",
		canvasLauncherBlank: "새 빈 Canvas — Vault 파일을 직접 올리기",
		canvasLauncherCurrent: (title: string) => `현재 노트로 시작 — ${title}`,
		canvasLauncherExisting: (title: string, path: string) => `기존 Canvas — ${title} · ${path}`,
		canvasPickerPlaceholder: "이 노트를 배치한 Canvas 선택…",
		canvasPickerItem: (title: string, path: string) => `${title} · ${path}`,
		graphsTitle: "저장된 그래프",
		graphsDescription: "저장된 그래프는 Markdown을 복제하지 않고 탐색 범위와 배치만 보관합니다.",
		noSavedGraphs: "저장된 그래프가 없습니다. Markdown 노트에서 ‘연결된 노트 읽기 지도 열기’를 실행한 뒤 현재 탐색을 저장하세요.",
		trashTitle: "원본 노트를 휴지통으로 이동할까요?",
		trashDescription: (title: string) => `“${title}” Markdown 원본을 휴지통으로 이동합니다. 이 노트를 사용하는 모든 그래프에서 사라집니다.`,
		reloadSourceTitle: "원문을 다시 불러올까요?",
		reloadSourceDescription: "현재 카드의 저장되지 않은 편집은 사라집니다. 먼저 ‘내 편집 선택’ 후 직접 복사해 내용을 보관할 수 있습니다.",
	},
		notice: {
		openMarkdownFirst: "먼저 Wiki 또는 Markdown 노트를 연 뒤 연결 보기를 실행하세요.",
		canvasCreated: "현재 노트로 Canvas를 만들었습니다. 필요한 파일을 직접 놓거나 연결 동기화를 켜세요.",
		blankCanvasCreated: "빈 Canvas를 만들었습니다. 파일 탐색기에서 Markdown·PDF·PNG·JPG·GIF를 끌어놓으세요.",
		canvasOpened: "기존 Linked Canvas를 열었습니다.",
		canvasOpenFailed: "이 노트의 Linked Canvas를 열지 못했습니다.",
		canvasCreateFailed: "Linked Canvas를 만들지 못했습니다.",
		openCanvasFirst: "먼저 Obsidian Canvas를 여세요.",
		canvasEnabled: "현재 Canvas에 연결 동기화를 켰습니다.",
		canvasAlreadyEnabled: "이 Canvas에는 이미 연결 동기화가 켜져 있습니다.",
		canvasEnableFailed: "Canvas에 Markdown 카드가 있는지 확인하세요.",
		canvasSynced: "Linked Canvas를 동기화했습니다.",
		canvasSyncFailed: "Linked Canvas를 동기화하지 못했습니다.",
		openLinkedCanvasFirst: "먼저 Linked Canvas를 여세요.",
		removedFromGraph: "현재 그래프에서만 제거했습니다.",
		removeFromGraphFailed: "현재 그래프에서 제거하지 못했습니다.",
		finishEditing: "열린 카드 편집을 먼저 저장하거나 취소하세요.",
		sourceMissing: "원문 노트를 찾을 수 없습니다.",
		openMarkdownFailed: "Markdown 편집기를 열지 못했습니다.",
		openSourceFailed: "원본 노트를 오른쪽에서 열지 못했습니다.",
		inlineSaveFailed: "Markdown 저장에 실패했습니다. 내용을 유지한 채 다시 시도합니다.",
		inlineSaveConflict: "다른 곳에서 수정된 원문을 감지했습니다. 현재 편집은 보존했고 자동 저장을 멈췄습니다.",
		inlineDraftSelected: "현재 편집을 선택했습니다. 필요하면 시스템 단축키로 복사하세요.",
		createFailed: "새 카드를 만들지 못했습니다.",
		connectFailed: "카드를 연결하지 못했습니다.",
		connectionRemoved: "연결을 삭제했습니다.",
		connectionRemoveFailed: "연결을 삭제하지 못했습니다.",
		connectionRemoveAmbiguous: "한 선에 여러 관계가 있어 여기서 삭제하지 않았습니다. 관계별 편집은 원문 Markdown에서 할 수 있습니다.",
		trashFailed: "원본 노트를 휴지통으로 이동하지 못했습니다.",
		graphDefinitionInvalid: "이 저장된 그래프 파일을 읽지 못했습니다. 파일 내용을 확인하세요.",
		renderFailed: "이 카드를 렌더링하지 못했습니다. 원문 노트에서 Markdown을 확인하세요.",
	},
};
