import type { COPY_KO } from "./copy-ko";

export const COPY_EN: typeof COPY_KO = {
	view: {
		title: "Context Graph",
		openCommand: "Show around current note",
		manageCommand: "Open saved graphs",
		refreshCommand: "Refresh graph",
		aria: "Knowledge graph. Drag to pan and use the mouse wheel to zoom.",
	},
	actions: {
		searchGraph: "Search graph",
		filterRelations: "Choose visible relations",
		saveGraph: "Save this graph",
		expandNeighbours: "Show neighbouring notes",
		collapseNeighbours: "Collapse neighbouring notes",
		removeFromGraph: "Remove from graph",
		newCard: "New card",
		createCard: "Create a card",
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
		resetView: "Fit graph",
		dragToConnect: "Drag to connect",
		pinCard: "Keep card open",
		unpinCard: "Stop keeping card open",
		editCard: "Edit Markdown in card",
		finishEditing: "Finish editing and return to Reading",
		copyDraft: "Copy my edit",
		reloadSource: "Reload source",
		openSource: "Open source",
		openSourceBesideGraph: "Open source in the right editor",
		more: "More",
		moveToTrash: "Move source note to trash…",
		cancel: "Cancel",
	},
	labels: {
		searchPlaceholder: "Search card titles, summaries, and content",
		relationFilters: "Visible relations",
		searchNoResults: "No matching cards",
		graphName: "Saved graph name",
		currentNoteGraphName: (title: string) => `Around ${title}`,
		newTopicTitle: "New topic",
		inlineMarkdownEditor: "Source Markdown editor",
		emptyTitle: "No notes in this graph",
		emptyFolderScope: (folder: string) => `No graph notes were found under “${folder}”.`,
		emptyCuratedScope: "No notes have been added to this graph yet.",
		emptyAllScope: "There are no notes to show in this graph yet.",
		emptyNextStep: "Open a Markdown note and show its surroundings to begin.",
	},
	relations: {
		derived: "Context",
		related: "Related",
		prerequisite: "Prerequisite",
		supports: "Supports",
		contrasts: "Contrasts",
		"follow-up": "Follow-up",
	},
	settings: {
		graphSettingsDescription: "Physics settings are stored separately for each saved graph.",
		physicsDescription: "Adjust how cards repel one another and how connections pull. This does not change Markdown or deliberate card positions.",
		linkStrengthName: "Link strength",
		linkStrengthDescription: "How strongly connected cards pull toward one another.",
		repulsionName: "Repulsion",
		repulsionDescription: "How strongly all cards push apart.",
		linkGapName: "Link gap",
		linkGapDescription: "The preferred space between the edges of connected cards.",
	},
	modal: {
		graphsTitle: "Saved graphs",
		graphsDescription: "Saved graphs keep an exploration range and layout without copying Markdown.",
		noSavedGraphs: "There are no saved graphs. Open the surroundings of a Markdown note, then save that exploration.",
		trashTitle: "Move the source note to trash?",
		trashDescription: (title: string) => `Move the Markdown source for “${title}” to trash. It will disappear from every graph that uses it.`,
		reloadSourceTitle: "Reload the source?",
		reloadSourceDescription: "Unsaved edits in this card will be discarded. Use “Copy my edit” first if you need to keep them.",
	},
	notice: {
		openMarkdownFirst: "Open a Markdown note first.",
		graphSaved: "Saved the current exploration.",
		graphSaveFailed: "Could not save the current exploration.",
		removedFromGraph: "Removed only from this graph.",
		removeFromGraphFailed: "Could not remove the note from this graph.",
		finishEditing: "Save or resolve the open card edit first.",
		sourceMissing: "The source note could not be found.",
		openMarkdownFailed: "Could not open the Markdown editor.",
		openSourceFailed: "Could not open the source note on the right.",
		inlineSaveFailed: "Markdown could not be saved. The edit is being kept for another attempt.",
		inlineSaveConflict: "The source changed elsewhere. Your edit is preserved and automatic saving has stopped.",
		inlineDraftCopied: "Copied the current edit to the clipboard.",
		createFailed: "Could not create a card.",
		connectFailed: "Could not connect the cards.",
		connectionRemoved: "Removed the connection.",
		connectionRemoveFailed: "Could not remove the connection.",
		connectionRemoveAmbiguous: "This line represents more than one relation, so nothing was removed. Edit individual relations in the source Markdown.",
		trashFailed: "Could not move the note to trash.",
		graphDefinitionInvalid: "This saved graph file could not be read. Check its contents.",
		renderFailed: "This card could not be rendered. Check its Markdown source.",
	},
};
