import type { COPY_KO } from "./copy-ko";

export const COPY_EN: typeof COPY_KO = {
	view: {
		title: "Note connections",
		openRibbon: "View current note connections",
		openCanvasCommand: "Advanced: open or create Canvas",
		helpCommand: "Show how to explore note connections",
		openCommand: "View current note connections",
		createCanvasCommand: "Advanced: create Canvas from current note",
		enableCanvasCommand: "Advanced: add linked cards to current Canvas",
		refreshCanvasCommand: "Advanced: refresh current Canvas links",
		manageCommand: "Advanced: saved graphs",
		refreshCommand: "Refresh current note connections",
		aria: "Knowledge graph. Drag to pan and use the mouse wheel to zoom.",
	},
	actions: {
		searchGraph: "Search graph",
		filterRelations: "Choose visible relations",
		continueInCanvas: "Continue in Canvas",
		expandNeighbours: "Show neighbouring notes",
		collapseNeighbours: "Collapse neighbouring notes",
		expandNeighboursCount: (count: number) => `Show ${count} neighbouring ${count === 1 ? "note" : "notes"}`,
		collapseNeighboursCount: (count: number) => count === 0
			? "Reset branch expansion (no notes hidden)"
			: `Collapse ${count} neighbouring ${count === 1 ? "note" : "notes"}`,
		removeFromGraph: "Remove from graph",
		newCard: "New card",
		createCard: "Create a card",
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
		resetView: "Fit graph",
		dragToConnect: "Drag to connect",
		pinCard: "Keep this card open while exploring",
		unpinCard: "Stop keeping this card open",
		editCard: "Edit Markdown in card",
		finishEditing: "Finish editing and return to Reading",
		selectDraft: "Select my edit",
		reloadSource: "Reload source",
		openSource: "Open source",
		openSourceBesideGraph: "Open source in the right editor",
		more: "More",
		moveToTrash: "Move source note to trash…",
		cancel: "Cancel",
	},
	labels: {
		roleRoot: "Root",
		roleTopic: "Topic",
		roleEntity: "Entity",
		roleQuestion: "Question",
		searchPlaceholder: "Search card titles, summaries, and content",
		relationFilters: "Visible relations",
		searchNoResults: "No matching cards",
		searchPanel: "Graph search and visible relations",
		graphToolbar: "Graph tools",
		cardLoading: "Loading Markdown…",
		currentNoteGraphName: (title: string) => `Around ${title}`,
		newTopicTitle: "New topic",
		inlineMarkdownEditor: "Source Markdown editor",
		emptyTitle: "No notes in this graph",
		emptyFolderScope: (folder: string) => `No graph notes were found under “${folder}”.`,
		emptyCuratedScope: "No notes have been added to this graph yet.",
		emptyAllScope: "There are no notes to show in this graph yet.",
		emptyNextStep: "Open a Markdown note, then open its linked-note reading map.",
		noVisibleLinks: "No linked notes are visible yet. Add a wikilink or backlink to grow this map.",
	},
	relations: {
		derived: "Context",
		related: "Related",
		prerequisite: "Prerequisite",
		supports: "Supports",
		contrasts: "Contrasts",
		"follow-up": "Follow-up",
	},
	settings: {
		helpName: "Get started with note connections",
		helpDescription: "Follow note wikilinks first and use Canvas only when spatial arrangement is useful.",
		helpButton: "How it works",
		graphSettingsDescription: "Physics settings are stored separately for each saved graph.",
		physicsDescription: "Adjust how cards repel one another and how connections pull. This does not change Markdown or deliberate card positions.",
		linkStrengthName: "Link strength",
		linkStrengthDescription: "How strongly connected cards pull toward one another.",
		repulsionName: "Repulsion",
		repulsionDescription: "How strongly all cards push apart.",
		linkGapName: "Link gap",
		linkGapDescription: "The preferred space between the edges of connected cards.",
	},
	help: {
		title: "How do I explore note connections?",
		intro: "Markdown [[wikilinks]] and backlinks are the relationship authority. Open a note, view its connections, and follow blue links into the source notes.",
		canvasEyebrow: "1 · Navigate in notes",
		canvasTitle: "Hyperlinks are the default",
		canvasDescription: "Click blue links in a Wiki note to open the connected source note. You do not need to create a Map or Canvas.",
		mapEyebrow: "2 · See connections at a glance",
		mapTitle: "View current note connections",
		mapDescription: "A supporting graph shows only real wikilinks, embeds, and backlinks around the current note. Open cards to read or move to the source editor.",
		existingEyebrow: "3 · Arrange material only when needed",
		existingTitle: "Canvas is an advanced tool",
		existingDescription: "Use a standard Canvas only when you need to arrange Markdown, PDFs, and images spatially. Normal Wiki navigation does not require it.",
		ownershipTitle: "What changes—and what stays yours?",
		ownershipItems: [
			"Wikilinks in the original Markdown are the only authority for document relationships.",
			"The note-connections view reads links without storing separate knowledge or relationships.",
			"A standard .canvas owns only positions, sizes, groups, and manual spatial notes; it never changes Markdown.",
			"An optional Canvas sidecar stores only the selected file scope and never copies source content.",
		],
		openCanvas: "Open advanced Canvas",
		openMap: "View current note connections",
	},
	modal: {
		canvasLauncherPlaceholder: "Advanced Canvas: create a new board or open a file…",
		canvasLauncherBlank: "New blank Canvas — place Vault files yourself",
		canvasLauncherCurrent: (title: string) => `Start with current note — ${title}`,
		canvasLauncherExisting: (title: string, path: string) => `Existing Canvas — ${title} · ${path}`,
		canvasPickerPlaceholder: "Choose a Canvas containing this note…",
		canvasPickerItem: (title: string, path: string) => `${title} · ${path}`,
		graphsTitle: "Saved graphs",
		graphsDescription: "Saved graphs keep an exploration range and layout without copying Markdown.",
		noSavedGraphs: "There are no saved graphs. Open a linked-note reading map, then save that exploration.",
		trashTitle: "Move the source note to trash?",
		trashDescription: (title: string) => `Move the Markdown source for “${title}” to trash. It will disappear from every graph that uses it.`,
		reloadSourceTitle: "Reload the source?",
		reloadSourceDescription: "Unsaved edits in this card will be discarded. Use “Select my edit” first if you need to copy them.",
	},
		notice: {
		openMarkdownFirst: "Open a Wiki or Markdown note before viewing its connections.",
		canvasCreated: "Created a Canvas from the current note. Place the files you need or enable link-aware sync.",
		blankCanvasCreated: "Created a blank Canvas. Drag Markdown, PDFs, PNG, JPG, and GIF files from File Explorer.",
		canvasOpened: "Opened an existing Linked Canvas.",
		canvasOpenFailed: "Could not open a Linked Canvas for this note.",
		canvasCreateFailed: "Could not create the Linked Canvas.",
		openCanvasFirst: "Open an Obsidian Canvas first.",
		canvasEnabled: "Enabled link-aware sync for this Canvas.",
		canvasAlreadyEnabled: "Link-aware sync is already enabled for this Canvas.",
		canvasEnableFailed: "Add at least one Markdown card to the Canvas and try again.",
		canvasSynced: "Synced the Linked Canvas.",
		canvasSyncFailed: "Could not sync the Linked Canvas.",
		openLinkedCanvasFirst: "Open a Linked Canvas first.",
		removedFromGraph: "Removed only from this graph.",
		removeFromGraphFailed: "Could not remove the note from this graph.",
		finishEditing: "Save or resolve the open card edit first.",
		sourceMissing: "The source note could not be found.",
		openMarkdownFailed: "Could not open the Markdown editor.",
		openSourceFailed: "Could not open the source note on the right.",
		inlineSaveFailed: "Markdown could not be saved. The edit is being kept for another attempt.",
		inlineSaveConflict: "The source changed elsewhere. Your edit is preserved and automatic saving has stopped.",
		inlineDraftSelected: "Selected the current edit. Copy it with your system shortcut if needed.",
		createFailed: "Could not create a card.",
		connectFailed: "Could not connect the cards.",
		connectionRemoved: "Removed the connection.",
		connectionRemoveFailed: "Could not remove the connection.",
		connectionRemoveAmbiguous: "This line represents more than one relation, so nothing was removed. Edit individual relations in the source Markdown.",
		trashFailed: "Could not move the note to trash.",
		graphDefinitionInvalid: "This saved graph file could not be read. Check its contents.",
		renderFailed: "This card could not be rendered. Check its Markdown source.",
	},
};
