export const COPY_KO = {
	view: {
		title: "Context Graph",
		openCommand: "현재 노트 주변 보기",
		manageCommand: "저장된 그래프 목록",
		refreshCommand: "그래프 새로고침",
		aria: "지식 그래프. 드래그로 이동하고 마우스 휠로 확대 또는 축소합니다.",
	},
	actions: {
		searchGraph: "그래프 검색",
		filterRelations: "관계 표시 설정",
		saveGraph: "이 그래프로 저장",
		expandNeighbours: "주변 노트 펼치기",
		collapseNeighbours: "주변 노트 접기",
		removeFromGraph: "그래프에서 제거",
		newCard: "새 카드",
		createCard: "새 카드 만들기",
		zoomIn: "확대",
		zoomOut: "축소",
		resetView: "전체 그래프 맞추기",
		dragToConnect: "연결점에서 끌기",
		pinCard: "카드 열어두기",
		unpinCard: "카드 열어두기 해제",
		editCard: "카드에서 Markdown 편집",
		finishEditing: "편집 마치고 읽기 모드로 전환",
		copyDraft: "내 편집 복사",
		reloadSource: "원문 다시 불러오기",
		openSource: "원문 열기",
		openSourceBesideGraph: "원본을 오른쪽 편집기로 열기",
		more: "더보기",
		moveToTrash: "원본 노트를 휴지통으로 이동…",
		cancel: "취소",
	},
	labels: {
		searchPlaceholder: "카드 제목·요약·본문 검색",
		relationFilters: "표시할 관계",
		searchNoResults: "일치하는 카드가 없습니다",
		graphName: "저장할 그래프 이름",
		currentNoteGraphName: (title: string) => `${title} 주변`,
		newTopicTitle: "새 주제",
		inlineMarkdownEditor: "원본 Markdown 편집기",
		emptyTitle: "포함된 노트가 없습니다",
		emptyFolderScope: (folder: string) => `“${folder}” 범위에서 그래프에 포함할 노트를 찾지 못했습니다.`,
		emptyCuratedScope: "이 그래프에는 아직 직접 추가한 노트가 없습니다.",
		emptyAllScope: "이 그래프에 표시할 노트가 아직 없습니다.",
		emptyNextStep: "Markdown 노트를 연 뒤 현재 노트 주변 보기를 시작하세요.",
	},
	relations: {
		derived: "맥락",
		related: "관련",
		prerequisite: "선수 지식",
		supports: "근거",
		contrasts: "비교·반례",
		"follow-up": "후속 질문",
	},
	settings: {
		graphSettingsDescription: "저장된 그래프마다 물리 설정을 독립적으로 보관합니다.",
		physicsDescription: "그래프의 모든 카드가 서로 밀고 연결선이 당기는 정도를 조절합니다. 화면 위치나 Markdown 내용은 바꾸지 않습니다.",
		linkStrengthName: "연결 강도",
		linkStrengthDescription: "연결된 카드가 서로 끌어당기는 힘입니다. 높을수록 연결된 항목이 가깝게 유지됩니다.",
		repulsionName: "반발력",
		repulsionDescription: "모든 카드가 서로 밀어내는 힘입니다. 높을수록 그래프가 넓게 퍼집니다.",
		linkGapName: "연결 간격",
		linkGapDescription: "연결된 카드 테두리 사이의 기본 여백입니다. 높을수록 관계선이 길어집니다.",
	},
	modal: {
		graphsTitle: "저장된 그래프",
		graphsDescription: "저장된 그래프는 Markdown을 복제하지 않고 탐색 범위와 배치만 보관합니다.",
		noSavedGraphs: "저장된 그래프가 없습니다. Markdown 노트에서 ‘현재 노트 주변 보기’를 연 뒤 현재 탐색을 저장하세요.",
		trashTitle: "원본 노트를 휴지통으로 이동할까요?",
		trashDescription: (title: string) => `“${title}” Markdown 원본을 휴지통으로 이동합니다. 이 노트를 사용하는 모든 그래프에서 사라집니다.`,
		reloadSourceTitle: "원문을 다시 불러올까요?",
		reloadSourceDescription: "현재 카드의 저장되지 않은 편집은 사라집니다. 먼저 ‘내 편집 복사’로 내용을 보관할 수 있습니다.",
	},
	notice: {
		openMarkdownFirst: "먼저 Markdown 노트를 여세요.",
		graphSaved: "현재 탐색을 저장했습니다.",
		graphSaveFailed: "현재 탐색을 저장하지 못했습니다.",
		removedFromGraph: "현재 그래프에서만 제거했습니다.",
		removeFromGraphFailed: "현재 그래프에서 제거하지 못했습니다.",
		finishEditing: "열린 카드 편집을 먼저 저장하거나 취소하세요.",
		sourceMissing: "원문 노트를 찾을 수 없습니다.",
		openMarkdownFailed: "Markdown 편집기를 열지 못했습니다.",
		openSourceFailed: "원본 노트를 오른쪽에서 열지 못했습니다.",
		inlineSaveFailed: "Markdown 저장에 실패했습니다. 내용을 유지한 채 다시 시도합니다.",
		inlineSaveConflict: "다른 곳에서 수정된 원문을 감지했습니다. 현재 편집은 보존했고 자동 저장을 멈췄습니다.",
		inlineDraftCopied: "현재 편집을 클립보드에 복사했습니다.",
		createFailed: "새 카드를 만들지 못했습니다.",
		connectFailed: "카드를 연결하지 못했습니다.",
		connectionRemoved: "연결을 삭제했습니다.",
		connectionRemoveFailed: "연결을 삭제하지 못했습니다.",
		connectionRemoveAmbiguous: "한 선에 여러 관계가 있어 여기서 삭제하지 않았습니다. 관계별 편집은 원문 Markdown에서 할 수 있습니다.",
		trashFailed: "원본 노트를 휴지통으로 이동하지 못했습니다.",
		graphDefinitionInvalid: "이 저장된 그래프 파일을 읽지 못했습니다. 파일 내용을 확인하세요.",
		renderFailed: "이 카드를 렌더링하지 못했습니다. 원문 노트에서 Markdown을 확인하세요.",
	},
};
